#!/usr/bin/env bash
# Install nginx with the -y option to assume yes to prompts
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
sudo cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Restart nginx using sudo to ensure proper permissions
sudo service nginx restart
